[package]
name = "rusty-gb"
version = "0.0.0"
authors = ["zrauf <zrauf@sfu.ca>", "rrcwang <rrcwang@g.ucla.edu>"]
edition = "2018"

[dependencies]
"thiserror" = "^1.0"

[dev-dependencies]
criterion = "^0.3"

[[bench]]
name = "benchmark"
harness = false
